[package]
name = "acts"
version = "0.1.0"
author = "Tor"
edition = "2021"


[dependencies]
derive_builder = "0.12.0"
iced = "0.8.0"
rusqlite = "0.28.0"
sentry = { version = "0.30.0", features = ["profiling"] }


